#!/bin/sh
# Uebungen zu HLR,, Blatt 3, Aufgabe 2, Version 06.11.2014
# SBATCH=sbatch	
# Time limit is one minute.
# See "man sbatch" for other time formats.
#SBATCH --time=1
# Run 16  tasks on 4 nodes.
#SBATCH -N 4 -n 16 
# Output goes to job.out, error messages to job.err.
#SBATCH --error=job_script.err --output=job_script.out
	
srun hostname

# Aufgabe 2.2
mpiexec ./timescript >> timescript.out

# Aufgabe 2.4 - Das funktioniert nicht
# mpiexec  ./timescript

echo "fertig" >> job_script.out


