#!/bin/bash
# Uebungen zu HLR, Blatt 3, Aufgabe 2, Version 06.11.2014

# Aufgabe 2.1:
echo "`hostname`: `date +"%d.%m.%Y %H:%M:%S,%N"`"

# Aufgabe 2.4: Das funktioniert so nicht
# echo "`hostname`: `date +"%d.%m.%Y %H:%M:%S,%N"`" >> timescript.out
