#!/bin/bash
# Script   ~/bin/timescript
# Uebungen zu HLR,, Blatt 3, Version 04.11.2014
TIMESTAMP=$( date  +"%d.%m.%Y %H:%M:%S,%N" )
HOST=$( hostname )
echo "$HOSTNAME: $TIMESTAMP" >> timescript.out
echo "$HOSTNAME: $TIMESTAMP - fertig" >> jobscript.out

